/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 */

/* Auto-generated by cbindgen. Do not edit by hand. */

#ifndef PAIMON_C_H
#define PAIMON_C_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque wrapper around a heap-allocated Rust object.
 */
typedef struct {
  void *inner;
} paimon_catalog;

/**
 * C-compatible byte buffer.
 */
typedef struct {
  uint8_t *data;
  uintptr_t len;
} paimon_bytes;

/**
 * C-compatible error type.
 */
typedef struct {
  int32_t code;
  paimon_bytes message;
} paimon_error;

typedef struct {
  paimon_catalog *catalog;
  paimon_error *error;
} paimon_result_catalog_new;

/**
 * C-compatible key-value pair for options.
 */
typedef struct {
  const char *key;
  const char *value;
} paimon_option;

typedef struct {
  void *inner;
} paimon_table;

typedef struct {
  paimon_table *table;
  paimon_error *error;
} paimon_result_get_table;

typedef struct {
  void *inner;
} paimon_identifier;

typedef struct {
  paimon_identifier *identifier;
  paimon_error *error;
} paimon_result_identifier_new;

typedef struct {
  void *inner;
} paimon_read_builder;

typedef struct {
  paimon_read_builder *read_builder;
  paimon_error *error;
} paimon_result_read_builder;

/**
 * Opaque wrapper around a Predicate.
 */
typedef struct {
  void *inner;
} paimon_predicate;

typedef struct {
  void *inner;
} paimon_table_scan;

typedef struct {
  paimon_table_scan *scan;
  paimon_error *error;
} paimon_result_table_scan;

typedef struct {
  void *inner;
} paimon_table_read;

typedef struct {
  paimon_table_read *read;
  paimon_error *error;
} paimon_result_new_read;

typedef struct {
  void *inner;
} paimon_plan;

typedef struct {
  paimon_plan *plan;
  paimon_error *error;
} paimon_result_plan;

typedef struct {
  void *inner;
} paimon_record_batch_reader;

typedef struct {
  paimon_record_batch_reader *reader;
  paimon_error *error;
} paimon_result_record_batch_reader;

/**
 * A single Arrow record batch exported via the Arrow C Data Interface.
 *
 * `array` and `schema` point to heap-allocated ArrowArray and ArrowSchema
 * structs. After importing the data, call `paimon_arrow_batch_free` to free
 * the container structs.
 */
typedef struct {
  /**
   * Pointer to a heap-allocated ArrowArray.
   */
  void *array;
  /**
   * Pointer to a heap-allocated ArrowSchema.
   */
  void *schema;
} paimon_arrow_batch;

typedef struct {
  paimon_arrow_batch batch;
  paimon_error *error;
} paimon_result_next_batch;

typedef struct {
  paimon_predicate *predicate;
  paimon_error *error;
} paimon_result_predicate;

/**
 * A typed literal value for predicate comparison, passed across FFI.
 *
 * # Design
 *
 * We use a tagged flat struct instead of opaque heap-allocated handles
 * (like DuckDB's `duckdb_value`). The trade-off:
 *
 * - **Pro**: Zero allocation — the entire datum is passed by value on the
 *   stack, with no heap round-trips or free calls needed. This keeps the
 *   FFI surface minimal and the Go/C caller simple.
 * - **Con**: The struct is larger than any single variant needs, wasting
 *   some bytes per datum (currently ~56 bytes vs. ~16 for the largest
 *   single variant).
 *
 * Since datums are only used for predicate construction (not a hot path),
 * the extra size is acceptable.
 *
 * # Tags
 *
 * - 0: Bool, 1: TinyInt, 2: SmallInt, 3: Int, 4: Long
 * - 5: Float, 6: Double, 7: String, 8: Date, 9: Time
 * - 10: Timestamp, 11: LocalZonedTimestamp, 12: Decimal, 13: Bytes
 *
 * `tag` determines which value fields are valid:
 * - `Bool`/`TinyInt`/`SmallInt`/`Int`/`Long`/`Date`/`Time` → `int_val`
 * - `Float`/`Double` → `double_val`
 * - `String`/`Bytes` → `str_data` + `str_len`
 * - `Timestamp`/`LocalZonedTimestamp` → `int_val` (millis) + `int_val2` (nanos)
 * - `Decimal` → `int_val` + `int_val2` (unscaled i128) + `uint_val` (precision) + `uint_val2` (scale)
 */
typedef struct {
  int32_t tag;
  int64_t int_val;
  double double_val;
  const uint8_t *str_data;
  uintptr_t str_len;
  int64_t int_val2;
  uint32_t uint_val;
  uint32_t uint_val2;
} paimon_datum;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a catalog using CatalogFactory with the given options.
 *
 * # Safety
 * `options` must be a valid pointer to an array of `paimon_option` with `options_len` elements.
 * Each key and value in the options must be valid null-terminated C strings.
 */

paimon_result_catalog_new paimon_catalog_create(const paimon_option *options,
                                                uintptr_t options_len)
;

/**
 * Free a paimon_catalog.
 *
 * # Safety
 * Only call with a catalog returned from `paimon_catalog_create`.
 */
 void paimon_catalog_free(paimon_catalog *catalog) ;

/**
 * Get a table from the catalog.
 *
 * # Safety
 * `catalog` and `identifier` must be valid pointers from previous paimon C calls, or null (returns error).
 */

paimon_result_get_table paimon_catalog_get_table(const paimon_catalog *catalog,
                                                 const paimon_identifier *identifier)
;

/**
 * Free a paimon_error.
 *
 * # Safety
 * Only call with errors returned from paimon C functions.
 */
 void paimon_error_free(paimon_error *err) ;

/**
 * Create a new Identifier.
 *
 * # Safety
 * `database` and `object` must be valid null-terminated C strings, or null (returns error).
 */
 paimon_result_identifier_new paimon_identifier_new(const char *database, const char *object) ;

/**
 * Free a paimon_identifier.
 *
 * # Safety
 * Only call with an identifier returned from `paimon_identifier_new`.
 */
 void paimon_identifier_free(paimon_identifier *id) ;

/**
 * Free a paimon_table.
 *
 * # Safety
 * Only call with a table returned from `paimon_catalog_get_table`.
 */
 void paimon_table_free(paimon_table *table) ;

/**
 * Create a new ReadBuilder from a Table.
 *
 * # Safety
 * `table` must be a valid pointer from `paimon_catalog_get_table`, or null (returns error).
 */
 paimon_result_read_builder paimon_table_new_read_builder(const paimon_table *table) ;

/**
 * Free a paimon_read_builder.
 *
 * # Safety
 * Only call with a read_builder returned from `paimon_table_new_read_builder`.
 */
 void paimon_read_builder_free(paimon_read_builder *rb) ;

/**
 * Set column projection for a ReadBuilder.
 *
 * The `columns` parameter is a null-terminated array of null-terminated C strings.
 * Output order follows the caller-specified order. Unknown or duplicate names
 * cause `paimon_read_builder_new_read()` to fail; an empty list is a valid
 * zero-column projection.
 *
 * # Safety
 * `rb` must be a valid pointer from `paimon_table_new_read_builder`, or null (returns error).
 * `columns` must be a null-terminated array of null-terminated C strings, or null for no projection.
 */

paimon_error *paimon_read_builder_with_projection(paimon_read_builder *rb,
                                                  const char *const *columns)
;

/**
 * Set a filter predicate for scan planning.
 *
 * The predicate is consumed (ownership transferred to the read builder).
 * Pass null to clear any previously set filter.
 *
 * # Safety
 * `rb` must be a valid pointer from `paimon_table_new_read_builder`, or null (returns error).
 * `predicate` must be a valid pointer from a `paimon_predicate_*` function, or null.
 */

paimon_error *paimon_read_builder_with_filter(paimon_read_builder *rb,
                                              paimon_predicate *predicate)
;

/**
 * Create a new TableScan from a ReadBuilder.
 *
 * # Safety
 * `rb` must be a valid pointer from `paimon_table_new_read_builder`, or null (returns error).
 */
 paimon_result_table_scan paimon_read_builder_new_scan(const paimon_read_builder *rb) ;

/**
 * Create a new TableRead from a ReadBuilder.
 *
 * # Safety
 * `rb` must be a valid pointer from `paimon_table_new_read_builder`, or null (returns error).
 */
 paimon_result_new_read paimon_read_builder_new_read(const paimon_read_builder *rb) ;

/**
 * Free a paimon_table_scan.
 *
 * # Safety
 * Only call with a scan returned from `paimon_read_builder_new_scan`.
 */
 void paimon_table_scan_free(paimon_table_scan *scan) ;

/**
 * Execute a scan plan to get splits.
 *
 * # Safety
 * `scan` must be a valid pointer from `paimon_read_builder_new_scan`, or null (returns error).
 */
 paimon_result_plan paimon_table_scan_plan(const paimon_table_scan *scan) ;

/**
 * Free a paimon_plan.
 *
 * # Safety
 * Only call with a plan returned from `paimon_table_scan_plan`.
 */
 void paimon_plan_free(paimon_plan *plan) ;

/**
 * Return the number of data splits in a plan.
 *
 * # Safety
 * `plan` must be a valid pointer from `paimon_table_scan_plan`, or null (returns 0).
 */
 uintptr_t paimon_plan_num_splits(const paimon_plan *plan) ;

/**
 * Free a paimon_table_read.
 *
 * # Safety
 * Only call with a read returned from `paimon_read_builder_new_read`.
 */
 void paimon_table_read_free(paimon_table_read *read) ;

/**
 * Read table data as Arrow record batches via a streaming reader.
 *
 * Returns a `paimon_record_batch_reader` that yields one batch at a time
 * via `paimon_record_batch_reader_next`. This avoids loading all batches
 * into memory at once.
 *
 * `offset` and `length` select a contiguous sub-range of splits from the
 * plan. The range is clamped to the available splits (out-of-range values
 * are silently adjusted).
 *
 * # Safety
 * `read` and `plan` must be valid pointers from previous paimon C calls, or null (returns error).
 */

paimon_result_record_batch_reader paimon_table_read_to_arrow(const paimon_table_read *read,
                                                             const paimon_plan *plan,
                                                             uintptr_t offset,
                                                             uintptr_t length)
;

/**
 * Get the next Arrow record batch from the reader.
 *
 * When the stream is exhausted, both `batch.array` and `batch.schema` will
 * be null. On error, `error` will be non-null.
 *
 * After importing each batch, call `paimon_arrow_batch_free` to free the
 * ArrowArray and ArrowSchema container structs.
 *
 * # Safety
 * `reader` must be a valid pointer from `paimon_table_read_to_arrow`, or null (returns error).
 */
 paimon_result_next_batch paimon_record_batch_reader_next(paimon_record_batch_reader *reader) ;

/**
 * Free a paimon_record_batch_reader.
 *
 * # Safety
 * Only call with a reader returned from `paimon_table_read_to_arrow`.
 */
 void paimon_record_batch_reader_free(paimon_record_batch_reader *reader) ;

/**
 * Free the ArrowArray and ArrowSchema container structs for a single batch.
 *
 * # Safety
 * `batch` must contain valid pointers returned by `paimon_record_batch_reader_next`.
 */
 void paimon_arrow_batch_free(paimon_arrow_batch batch) ;

/**
 * Create an equality predicate: `column = datum`.
 *
 * # Safety
 * `table` and `column` must be valid pointers.
 */

paimon_result_predicate paimon_predicate_equal(const paimon_table *table,
                                               const char *column,
                                               paimon_datum datum)
;

/**
 * Create a not-equal predicate: `column != datum`.
 *
 * # Safety
 * `table` and `column` must be valid pointers.
 */

paimon_result_predicate paimon_predicate_not_equal(const paimon_table *table,
                                                   const char *column,
                                                   paimon_datum datum)
;

/**
 * Create a less-than predicate: `column < datum`.
 *
 * # Safety
 * `table` and `column` must be valid pointers.
 */

paimon_result_predicate paimon_predicate_less_than(const paimon_table *table,
                                                   const char *column,
                                                   paimon_datum datum)
;

/**
 * Create a less-or-equal predicate: `column <= datum`.
 *
 * # Safety
 * `table` and `column` must be valid pointers.
 */

paimon_result_predicate paimon_predicate_less_or_equal(const paimon_table *table,
                                                       const char *column,
                                                       paimon_datum datum)
;

/**
 * Create a greater-than predicate: `column > datum`.
 *
 * # Safety
 * `table` and `column` must be valid pointers.
 */

paimon_result_predicate paimon_predicate_greater_than(const paimon_table *table,
                                                      const char *column,
                                                      paimon_datum datum)
;

/**
 * Create a greater-or-equal predicate: `column >= datum`.
 *
 * # Safety
 * `table` and `column` must be valid pointers.
 */

paimon_result_predicate paimon_predicate_greater_or_equal(const paimon_table *table,
                                                          const char *column,
                                                          paimon_datum datum)
;

/**
 * Create an IS NULL predicate.
 *
 * # Safety
 * `table` and `column` must be valid pointers.
 */
 paimon_result_predicate paimon_predicate_is_null(const paimon_table *table, const char *column) ;

/**
 * Create an IS NOT NULL predicate.
 *
 * # Safety
 * `table` and `column` must be valid pointers.
 */

paimon_result_predicate paimon_predicate_is_not_null(const paimon_table *table,
                                                     const char *column)
;

/**
 * Create an IN predicate: `column IN (datum1, datum2, ...)`.
 *
 * # Safety
 * `table`, `column`, and `datums` must be valid pointers. `datums_len` must be the length.
 */

paimon_result_predicate paimon_predicate_is_in(const paimon_table *table,
                                               const char *column,
                                               const paimon_datum *datums,
                                               uintptr_t datums_len)
;

/**
 * Create a NOT IN predicate: `column NOT IN (datum1, datum2, ...)`.
 *
 * # Safety
 * `table`, `column`, and `datums` must be valid pointers. `datums_len` must be the length.
 */

paimon_result_predicate paimon_predicate_is_not_in(const paimon_table *table,
                                                   const char *column,
                                                   const paimon_datum *datums,
                                                   uintptr_t datums_len)
;

/**
 * Combine two predicates with AND. Consumes both inputs.
 *
 * # Safety
 * `a` and `b` must be valid pointers from predicate functions.
 */
 paimon_predicate *paimon_predicate_and(paimon_predicate *a, paimon_predicate *b) ;

/**
 * Combine two predicates with OR. Consumes both inputs.
 *
 * # Safety
 * `a` and `b` must be valid pointers from predicate functions.
 */
 paimon_predicate *paimon_predicate_or(paimon_predicate *a, paimon_predicate *b) ;

/**
 * Negate a predicate with NOT. Consumes the input.
 *
 * # Safety
 * `p` must be a valid pointer from a predicate function.
 */
 paimon_predicate *paimon_predicate_not(paimon_predicate *p) ;

/**
 * Free a paimon_predicate.
 *
 * # Safety
 * Only call with a predicate returned from paimon predicate functions.
 */
 void paimon_predicate_free(paimon_predicate *p) ;

/**
 * Free a paimon_bytes buffer.
 *
 * # Safety
 * Only call with bytes returned from paimon C functions.
 */
 void paimon_bytes_free(paimon_bytes bytes) ;

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PAIMON_C_H */
